### PR TITLE
Accept infinite function paramaters

### PR DESCRIPTION
**Pull request by appleplectic**

### CODE REVIEW

**Comment by ppaska** [comment]
Very good catch @appleplectic . Thanks for that.
I will be happy to accept your PR. But, there is one other place that needs to be changed. Please have a look at evaluatorAsync https://github.com/jspython-dev/jspython/blob/8d9839820141dd11be7479669097bc1c30f0777c/src/evaluator/evaluatorAsync.ts#L166 

At the moment, evaluator and evaluatorAsync contain duplicated logic. This will be refactored in the nearest future. But, for now, we have to maintain the same logic in both files.

Thanks,
Pavlo

**Review by ppaska — COMMENTED** [review]
please apply the same changes to invokeFunctionAsync
https://github.com/jspython-dev/jspython/blob/8d9839820141dd11be7479669097bc1c30f0777c/src/evaluator/evaluatorAsync.ts#L166

**Review by ppaska — CHANGES_REQUESTED** [review]
evaluatorAsync needs to be changed as well
https://github.com/jspython-dev/jspython/blob/8d9839820141dd11be7479669097bc1c30f0777c/src/evaluator/evaluatorAsync.ts#L166

**Comment by LordPupuce** [comment]
@appleplectic is not spreading the correct parameter. He is spreading `args` when he should be spreading `fps`

**Review by appleplectic — COMMENTED** [review]
Changed the other function and spread fps

**Pull request merged**
